package gt.com.ro.devumgapp.notificacion.ui;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import android.view.*; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import androidx.core.app.ActivityCompat; import androidx.core.content.ContextCompat; import com.google.android.material.appbar.MaterialToolbar; import com.google.android.material.card.MaterialCardView; import com.google.android.material.dialog.MaterialAlertDialogBuilder; import java.util.*; import gt.com.ro.devumgapp.R; import gt.com.ro.devumgapp.academico.ui.*; import gt.com.ro.devumgapp.auth.ui.*; import gt.com.ro.devumgapp.core.network.RetrofitClient; import gt.com.ro.devumgapp.core.session.*; import gt.com.ro.devumgapp.notificacion.NotificationApi; import gt.com.ro.devumgapp.notificacion.NotificationModels; import gt.com.ro.devumgapp.core.dto.PageResponse; import retrofit2.*;
public class NotificationInboxActivity extends AppCompatActivity {
 public static final String EXTRA_NOTIFICATION_ID="notificationId"; private static final int REQ_PUSH=881; private static volatile boolean visible; private LinearLayout rows;private ProgressBar progress;private NotificationApi api;private MaterialToolbar toolbar;private int page=0;private boolean loading;
 public static boolean isVisible(){return visible;}
 @Override protected void onCreate(Bundle b){super.onCreate(b);if(!SessionManager.getInstance().isLoggedIn()){SessionManager.handleUnauthorized(this);return;}api=RetrofitClient.getClient().create(NotificationApi.class);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);toolbar=new MaterialToolbar(this);toolbar.setTitle("Notificaciones");toolbar.setNavigationIcon(R.drawable.ic_arrow_back);toolbar.setNavigationOnClickListener(v->finish());root.addView(toolbar);LinearLayout actions=new LinearLayout(this);Button all=new Button(this);all.setText("Marcar todas como leídas");all.setOnClickListener(v->readAll());Button clear=new Button(this);clear.setText("Vaciar buzón");clear.setOnClickListener(v->confirmClear());actions.addView(all,new LinearLayout.LayoutParams(0,-2,1));actions.addView(clear,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);progress=new ProgressBar(this);progress.setVisibility(View.GONE);root.addView(progress);ScrollView scroll=new ScrollView(this);rows=new LinearLayout(this);rows.setOrientation(LinearLayout.VERTICAL);rows.setPadding(dp(16),dp(12),dp(16),dp(24));scroll.addView(rows);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));Button more=new Button(this);more.setText("Cargar más");more.setOnClickListener(v->load(false));root.addView(more);setContentView(root);askPushPermission();load(true);String id=getIntent().getStringExtra(EXTRA_NOTIFICATION_ID);if(id!=null)openPush(id);}
 @Override protected void onResume(){super.onResume();visible=true;}@Override protected void onPause(){visible=false;super.onPause();}
 private void askPushPermission(){if(Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)return;boolean asked=getPreferences(0).getBoolean("push_asked",false);if(asked)return;new MaterialAlertDialogBuilder(this).setTitle("Recibir avisos de SGAU").setMessage("Puedes activar avisos discretos cuando haya novedades. El buzón seguirá disponible si los omites.").setNegativeButton("Ahora no",(d,w)->getPreferences(0).edit().putBoolean("push_asked",true).apply()).setPositiveButton("Activar",(d,w)->{getPreferences(0).edit().putBoolean("push_asked",true).apply();ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_PUSH);}).show();}
 private void load(boolean reset){if(loading)return;loading=true;progress.setVisibility(View.VISIBLE);if(reset){page=0;rows.removeAllViews();}api.list(page,20).enqueue(new Callback<PageResponse<NotificationModels.Item>>(){public void onResponse(Call<PageResponse<NotificationModels.Item>>c,Response<PageResponse<NotificationModels.Item>>r){loading=false;progress.setVisibility(View.GONE);if(!r.isSuccessful()||r.body()==null){empty("No se pudo cargar el buzón.",true);return;}List<NotificationModels.Item>items=r.body().content;if(items==null||items.isEmpty()){if(page==0)empty("Tu buzón está vacío.",false);return;}for(NotificationModels.Item item:items)addItem(item);page++;}public void onFailure(Call<PageResponse<NotificationModels.Item>>c,Throwable t){loading=false;progress.setVisibility(View.GONE);empty("Sin conexión. Toca para reintentar.",true);}});}
 private void addItem(NotificationModels.Item n){
  MaterialCardView card=new MaterialCardView(this);card.setRadius(dp(16));card.setCardElevation(dp(2));card.setStrokeWidth(dp(1));card.setStrokeColor(ContextCompat.getColor(this,n.leida?R.color.dashboard_border:R.color.dashboard_primary));
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(16),dp(18),dp(14));
  LinearLayout heading=new LinearLayout(this);heading.setOrientation(LinearLayout.HORIZONTAL);heading.setGravity(Gravity.CENTER_VERTICAL);
  TextView title=text(n.titulo,17,true);title.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));heading.addView(title);
  TextView status=text(n.leida?"LEÍDA":"NUEVA",10,true);status.setTextColor(ContextCompat.getColor(this,n.leida?R.color.dashboard_text_secondary:R.color.dashboard_primary));status.setPadding(dp(9),dp(5),dp(9),dp(5));heading.addView(status);
  TextView message=text(n.mensaje,15,false);message.setTextColor(ContextCompat.getColor(this,R.color.dashboard_text_secondary));message.setPadding(0,dp(8),0,dp(6));
  TextView date=text(n.fechaCreacion,12,false);date.setTextColor(ContextCompat.getColor(this,R.color.dashboard_text_secondary));
  box.addView(heading);box.addView(message);box.addView(date);
  LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);actions.setPadding(0,dp(8),0,0);
  com.google.android.material.button.MaterialButton read=new com.google.android.material.button.MaterialButton(this);read.setText(n.leida?"Leída":"Marcar leída");read.setEnabled(!n.leida);read.setTextSize(12);read.setInsetTop(0);read.setInsetBottom(0);read.setCornerRadius(dp(10));read.setOnClickListener(v->api.read(n.id).enqueue(new Callback<NotificationModels.Item>(){public void onResponse(Call<NotificationModels.Item>c,Response<NotificationModels.Item>r){load(true);}public void onFailure(Call<NotificationModels.Item>c,Throwable t){Toast.makeText(NotificationInboxActivity.this,"No se pudo marcar como leída.",Toast.LENGTH_SHORT).show();}}));
  com.google.android.material.button.MaterialButton delete=new com.google.android.material.button.MaterialButton(this,null,com.google.android.material.R.attr.materialButtonOutlinedStyle);delete.setText("Eliminar");delete.setTextSize(12);delete.setInsetTop(0);delete.setInsetBottom(0);delete.setCornerRadius(dp(10));delete.setOnClickListener(v->api.delete(n.id).enqueue(new Callback<Void>(){public void onResponse(Call<Void>c,Response<Void>r){load(true);}public void onFailure(Call<Void>c,Throwable t){Toast.makeText(NotificationInboxActivity.this,"No se pudo eliminar.",Toast.LENGTH_SHORT).show();}}));
  actions.addView(read);LinearLayout.LayoutParams delParams=new LinearLayout.LayoutParams(-2,-2);delParams.leftMargin=dp(8);actions.addView(delete,delParams);box.addView(actions);card.addView(box);card.setCardBackgroundColor(ContextCompat.getColor(this,R.color.dashboard_surface));card.setOnClickListener(v->open(n));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);rows.addView(card,p);
 }
 private void openPush(String id){try{long nid=Long.parseLong(id);api.get(nid).enqueue(new Callback<NotificationModels.Item>(){public void onResponse(Call<NotificationModels.Item>c,Response<NotificationModels.Item>r){if(!r.isSuccessful()||r.body()==null){empty("Esta notificación no pertenece a esta cuenta o ya no está disponible.",true);return;}open(r.body());}public void onFailure(Call<NotificationModels.Item>c,Throwable t){empty("No se pudo verificar el aviso en el servidor.",true);}});}catch(NumberFormatException e){empty("El aviso no es válido.",true);}}
 private void open(NotificationModels.Item n){api.read(n.id).enqueue(new Callback<NotificationModels.Item>(){public void onResponse(Call<NotificationModels.Item>c,Response<NotificationModels.Item>r){if(!r.isSuccessful()){Toast.makeText(NotificationInboxActivity.this,"La notificación ya no está disponible.",Toast.LENGTH_LONG).show();return;}if("REVISION_PAGO".equals(n.destinoTipo)){if(!Permissions.hasRole("ADMIN")||!Permissions.has(Permissions.COLEGIATURAS_CAMBIAR_ESTADO)){Toast.makeText(NotificationInboxActivity.this,"No tienes permiso para revisar pagos.",Toast.LENGTH_LONG).show();return;}Intent review=new Intent(NotificationInboxActivity.this,gt.com.ro.devumgapp.colegiatura.ui.RevisionPagosActivity.class);if(n.destinoId!=null)review.putExtra("paymentId",n.destinoId);startActivity(review);finish();return;}int dest=R.id.nav_cursos;if("NOTA".equals(n.destinoTipo))dest=R.id.nav_notas;else if("COLEGIATURA".equals(n.destinoTipo))dest=R.id.nav_colegiaturas;Intent i;if(Permissions.hasRole("ESTUDIANTE")){i=new Intent(NotificationInboxActivity.this,EstudianteAcademicActivity.class).putExtra(HomeActivity.EXTRA_CURRENT_DESTINATION,dest);}else if(Permissions.hasRole("DOCENTE")){i=new Intent(NotificationInboxActivity.this,DocenteAcademicActivity.class).putExtra(HomeActivity.EXTRA_CURRENT_DESTINATION,dest);}else{i=new Intent(NotificationInboxActivity.this,HomeActivity.class).putExtra(HomeActivity.EXTRA_CURRENT_DESTINATION,dest);}if(n.destinoId!=null)i.putExtra("notificationDestinationId",n.destinoId);startActivity(i);finish();}public void onFailure(Call<NotificationModels.Item>c,Throwable t){Toast.makeText(NotificationInboxActivity.this,"No se pudo abrir el destino.",Toast.LENGTH_LONG).show();}});}
 private void readAll(){api.readAll().enqueue(new Callback<Map<String,Integer>>(){public void onResponse(Call<Map<String,Integer>>c,Response<Map<String,Integer>>r){load(true);}public void onFailure(Call<Map<String,Integer>>c,Throwable t){Toast.makeText(NotificationInboxActivity.this,"No se pudo actualizar el buzón.",Toast.LENGTH_SHORT).show();}});}
 private void confirmClear(){new MaterialAlertDialogBuilder(this).setTitle("Vaciar buzón").setMessage("Se eliminarán únicamente tus notificaciones de SGAU. La auditoría académica no se modifica.").setNegativeButton("Cancelar",null).setPositiveButton("Vaciar",(d,w)->api.clear().enqueue(new Callback<Map<String,Integer>>(){public void onResponse(Call<Map<String,Integer>>c,Response<Map<String,Integer>>r){load(true);}public void onFailure(Call<Map<String,Integer>>c,Throwable t){Toast.makeText(NotificationInboxActivity.this,"No se pudo vaciar el buzón.",Toast.LENGTH_SHORT).show();}})).show();}
 private void empty(String message,boolean retry){TextView t=text(message,15,false);rows.addView(t);if(retry){Button b=new Button(this);b.setText("Reintentar");b.setOnClickListener(v->load(true));rows.addView(b);}}private TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s==null?"":s);t.setTextSize(size);if(bold)t.setTypeface(null,1);t.setTextColor(ContextCompat.getColor(this,R.color.dashboard_text_primary));return t;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
