package gt.com.ro.devumgapp.notificacion.push;
import android.app.*; import android.content.*; import android.os.Build; import androidx.core.app.NotificationCompat; import com.google.firebase.messaging.*; import gt.com.ro.devumgapp.R; import gt.com.ro.devumgapp.auth.ui.LoginActivity; import gt.com.ro.devumgapp.auth.ui.HomeActivity; import gt.com.ro.devumgapp.core.session.SessionManager;
import gt.com.ro.devumgapp.notificacion.ui.NotificationInboxActivity;
public class SgauFirebaseMessagingService extends FirebaseMessagingService {
 public static final String CHANNEL="sgau_updates";
 @Override public void onNewToken(String token){if(SessionManager.getInstance().isLoggedIn())gt.com.ro.devumgapp.notificacion.PushRegistrationManager.register(this);}
 @Override public void onMessageReceived(RemoteMessage message){String id=message.getData().get("notificationId");if(id==null||gt.com.ro.devumgapp.App.isForeground())return;createChannel();Intent intent;if(SessionManager.getInstance().isLoggedIn()){intent=new Intent(this,NotificationInboxActivity.class);intent.putExtra(NotificationInboxActivity.EXTRA_NOTIFICATION_ID,id);}else{intent=new Intent(this, LoginActivity.class);intent.putExtra("pendingNotificationId",id);}intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pending=PendingIntent.getActivity(this,id.hashCode(),intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new NotificationCompat.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_sgau_logo).setContentTitle("SGAU · Nueva notificación").setContentText("Abre SGAU para consultar una actualización.").setContentIntent(pending).setAutoCancel(true).setVisibility(NotificationCompat.VISIBILITY_PRIVATE).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(id.hashCode(),n);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager m=getSystemService(NotificationManager.class);if(m.getNotificationChannel(CHANNEL)==null)m.createNotificationChannel(new NotificationChannel(CHANNEL,"Actualizaciones SGAU",NotificationManager.IMPORTANCE_DEFAULT));}}
}
