package gt.com.ro.devumgapp.academico.ui;

import android.os.Bundle;
import android.app.DatePickerDialog;
import android.text.InputType;
import android.view.View;
import android.widget.*;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.textfield.*;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.*;
import gt.com.ro.devumgapp.R;
import gt.com.ro.devumgapp.academico.dto.AcademicDtos.*;
import gt.com.ro.devumgapp.academico.network.AcademicoApiService;
import gt.com.ro.devumgapp.auth.ui.HomeActivity;
import gt.com.ro.devumgapp.core.dto.PageResponse;
import gt.com.ro.devumgapp.core.network.RetrofitClient;
import gt.com.ro.devumgapp.core.session.*;
import gt.com.ro.devumgapp.core.ui.ModuleNavigation;
import gt.com.ro.devumgapp.notificacion.NotificationBadge;
import retrofit2.*;

/** Módulos de consulta del estudiante; todos consumen rutas /me sin aceptar un estudianteId. */
public class EstudianteAcademicActivity extends AcademicBaseActivity {
    private static final int PAGE_SIZE=200;
    private AcademicoApiService api; private int pending,mode;
    private final List<Call<?>> calls=new ArrayList<>();
    @Override protected void onCreate(Bundle state){super.onCreate(state);if(!SessionManager.getInstance().isLoggedIn()){SessionManager.handleUnauthorized(this);return;}if(!Permissions.hasRole("ESTUDIANTE")){finish();return;}setContentView(R.layout.activity_academic_overview);content=findViewById(R.id.academicContent);progress=findViewById(R.id.progressAcademic);mode=getIntent().getIntExtra(HomeActivity.EXTRA_CURRENT_DESTINATION,R.id.nav_carreras);MaterialToolbar bar=findViewById(R.id.toolbarAcademic);bar.setTitle(title());ModuleNavigation.attach(this,bar);NotificationBadge.attach(this,bar);configureHero(title(),subtitle(),hero(),icon(),R.color.dashboard_student);api=RetrofitClient.getClient().create(AcademicoApiService.class);load();}
    private String title(){if(mode==R.id.nav_cursos)return"Mis cursos";if(mode==R.id.nav_notas)return"Mis notas";if(mode==R.id.nav_colegiaturas)return"Colegiatura";return"Mi carrera";}
    private String subtitle(){if(mode==R.id.nav_cursos)return"Cursos en los que estás inscrito";if(mode==R.id.nav_notas)return"Evaluaciones registradas por curso";if(mode==R.id.nav_colegiaturas)return"Estado de cuenta y pagos en revisión";return"Plan de estudios y avance de créditos";}
    private int hero(){return mode==R.id.nav_colegiaturas?R.drawable.bg_colegiatura_header:mode==R.id.nav_notas?R.drawable.bg_nota_header:mode==R.id.nav_cursos?R.drawable.bg_curso_header:R.drawable.bg_estudiante_header;}
    private int icon(){return mode==R.id.nav_colegiaturas?R.drawable.ic_payment:mode==R.id.nav_notas?R.drawable.ic_grade:mode==R.id.nav_cursos?R.drawable.ic_course:R.drawable.ic_career;}
    private void load(){content.removeAllViews();loading(true);calls.clear();if(mode==R.id.nav_cursos)loadCourses();else if(mode==R.id.nav_notas){pending=1;request(api.notasEstudianteFiltradas(null,0,PAGE_SIZE),p->grades(items(p)));}else if(mode==R.id.nav_colegiaturas){pending=2;request(api.colegiaturas(0,PAGE_SIZE),p->tuition(items(p)));request(api.pagos(),this::payments);}else{pending=1;request(api.carrerasDisponibles(),available->{if(available!=null&&!available.isEmpty()){careerOptions(available);}else{pending++;request(api.planCarreraEstudiante(),this::career);}});}}
    private void careerOptions(List<CarreraDisponible> options){content.addView(section("Carreras disponibles"));content.addView(messageCard("Elige una carrera para iniciar tu inscripción. La mensualidad se cobra por ciclo académico.",false));for(CarreraDisponible c:options){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.addView(card(s(c.codigo)+" · "+s(c.nombre),"Mensualidad: Q"+money(c.mensualidad==null?0:c.mensualidad.doubleValue())+" · "+c.cantidadCuotas+" cuotas · vence el día "+c.diaVencimiento));if(Permissions.has(Permissions.INSCRIPCIONES_CREAR)){Button enroll=new Button(this);enroll.setText("Inscribirme");enroll.setOnClickListener(v->startEnrollment(c));row.addView(enroll);}content.addView(row);}}
    private void startEnrollment(CarreraDisponible c){api.ciclosDisponibles().enqueue(new Callback<List<Ciclo>>(){public void onResponse(Call<List<Ciclo>>q,Response<List<Ciclo>>r){if(!r.isSuccessful()||r.body()==null||r.body().isEmpty()){error("No hay ciclos académicos disponibles.");return;}choose(r.body(),"Selecciona el ciclo",cycle->api.gradosDisponibles().enqueue(new Callback<List<Grado>>(){public void onResponse(Call<List<Grado>>z,Response<List<Grado>>g){if(!g.isSuccessful()||g.body()==null||g.body().isEmpty()){error("No hay grados configurados.");return;}choose(g.body(),"Selecciona el grado",grade->api.seccionesDisponibles(grade.id).enqueue(new Callback<List<Seccion>>(){public void onResponse(Call<List<Seccion>>k,Response<List<Seccion>>sr){if(!sr.isSuccessful()||sr.body()==null||sr.body().isEmpty()){error("No hay secciones disponibles para ese grado.");return;}choose(sr.body(),"Selecciona la sección",section->confirmEnrollment(c,cycle,grade,section));}public void onFailure(Call<List<Seccion>>k,Throwable t){error("No se pudieron cargar las secciones.");}}));}public void onFailure(Call<List<Grado>>z,Throwable t){error("No se pudieron cargar los grados.");}}));}public void onFailure(Call<List<Ciclo>>q,Throwable t){error("No se pudieron cargar los fechas del ciclo.");}});}
    private <T>void choose(List<T> values,String title,java.util.function.Consumer<T> picked){new MaterialAlertDialogBuilder(this).setTitle(title).setItems(values.stream().map(Object::toString).toArray(String[]::new),(d,w)->picked.accept(values.get(w))).setNegativeButton("Cancelar",null).show();}
    private void confirmEnrollment(CarreraDisponible c,Ciclo cycle,Grado grade,Seccion section){StringBuilder quote=new StringBuilder("Carrera: ").append(c.nombre).append("\nPeríodo: ").append(cycle.nombre).append(" · ").append(cycle.anio).append(" (").append(cycle.fechaInicio).append(" a ").append(cycle.fechaFin).append(")\nGrado/sección: ").append(grade.nombre).append(" · ").append(section.nombre).append("\nMensualidad: Q").append(money(c.mensualidad.doubleValue())).append("\nCuotas previstas:\n");try{LocalDate start=LocalDate.parse(cycle.fechaInicio);for(int n=1;n<=c.cantidadCuotas;n++){LocalDate emission=start.plusMonths(n-1);YearMonth month=YearMonth.from(emission);LocalDate due=month.atDay(Math.min(c.diaVencimiento,month.lengthOfMonth()));quote.append("Cuota ").append(n).append(": Q").append(money(c.mensualidad.doubleValue())).append(" · vence ").append(due).append("\n");}}catch(Exception ignored){quote.append(c.cantidadCuotas).append(" cuotas mensuales con vencimiento el día ").append(c.diaVencimiento).append(".\n");}quote.append("El importe se genera una vez por carrera y período; no se multiplica por cursos.");new MaterialAlertDialogBuilder(this).setTitle("Confirmar inscripción").setMessage(quote.toString()).setNegativeButton("Cancelar",null).setPositiveButton("Confirmar",(d,w)->{SolicitudInscripcion request=new SolicitudInscripcion();request.carreraId=c.id;request.cicloId=cycle.id;request.gradoId=grade.id;request.seccionId=section.id;api.inscribirse(request).enqueue(new Callback<Object>(){public void onResponse(Call<Object>q,Response<Object>r){if(r.isSuccessful()){Toast.makeText(EstudianteAcademicActivity.this,"Inscripción confirmada y colegiaturas generadas.",Toast.LENGTH_LONG).show();load();}else error(AcademicErrors.from(EstudianteAcademicActivity.this,r));}public void onFailure(Call<Object>q,Throwable t){error("No se pudo completar la inscripción.");}});}).show();}
    private void loadCourses(){pending=2;request(api.cursosInscritosEstudiante(),rows->request(api.docentesEstudiante(),teachers->courses(rows,teachers)));}
    private <T>void request(Call<T>call,java.util.function.Consumer<T>ok){calls.add(call);call.enqueue(new Callback<T>(){public void onResponse(Call<T>c,Response<T>r){if(r.isSuccessful()&&r.body()!=null)ok.accept(r.body());else error(AcademicErrors.from(EstudianteAcademicActivity.this,r));done();}public void onFailure(Call<T>c,Throwable t){if(!c.isCanceled())error("No se pudo cargar la información. Revisa tu conexión.");done();}});}
    private void career(PlanCarrera p){content.addView(section("Carrera asignada"));content.addView(card(s(p.carrera.codigo)+" · "+s(p.carrera.nombre),s(p.carrera.descripcion)));content.addView(card("Créditos del plan: "+p.totalCreditosPlan,"Créditos inscritos: "+p.totalCreditosInscritos));content.addView(section("Cursos del plan"));List<CursoPlan>rows=p.cursosDisponibles==null?Collections.emptyList():p.cursosDisponibles;if(rows.isEmpty())content.addView(messageCard("No hay cursos en el plan.",false));for(CursoPlan c:rows){String periodo=c.cicloNombre==null?"Año académico "+c.cicloAnio:"Oferta "+c.cicloNombre+" · "+c.cicloAnio;content.addView(card(s(c.codigo)+" · "+s(c.nombre),c.creditos+" créditos · "+periodo+" · "+(c.docenteNombre==null?"Sin docente":c.docenteNombre)+(c.inscrito?" · Inscrito":" · Disponible")));if(!c.inscrito&&Permissions.has(Permissions.INSCRIPCIONES_CREAR)){Button assign=new Button(this);assign.setText("Asignarme");assign.setOnClickListener(v->new MaterialAlertDialogBuilder(this).setTitle("Asignarme al curso").setMessage(c.nombre+" ("+c.codigo+")\nCréditos: "+c.creditos+"\nDocente: "+s(c.docenteNombre)+"\n"+periodo).setNegativeButton("Cancelar",null).setPositiveButton("Confirmar",(d,w)->api.asignarCurso(c.id).enqueue(new Callback<Object>(){public void onResponse(Call<Object>q,Response<Object>r){if(r.isSuccessful()){Toast.makeText(EstudianteAcademicActivity.this,"Asignación confirmada.",Toast.LENGTH_SHORT).show();load();}else error(AcademicErrors.from(EstudianteAcademicActivity.this,r));}public void onFailure(Call<Object>q,Throwable t){error("No se pudo asignar el curso.");}})).show());content.addView(assign);}}}
    private void courses(List<Curso>rows,List<DocenteCurso>teachers){content.addView(section("Cursos inscritos"));if(rows==null||rows.isEmpty()){content.addView(messageCard("No tienes cursos inscritos.",false));return;}long requested=getIntent().getLongExtra("notificationDestinationId",-1);for(Curso c:rows){String teacher="Sin docente asignado";for(DocenteCurso d:teachers)if(d.cursoId==c.id){teacher="Docente: "+s(d.nombre)+" "+s(d.apellido);break;}String periodo=c.cicloNombre==null?(c.cicloAnio>0?"Año académico "+c.cicloAnio:""):"Oferta "+c.cicloNombre+" · "+c.cicloAnio;String detail=c.creditos+" créditos · "+teacher+(periodo.isEmpty()?"":" · "+periodo);View v=card(s(c.codigo)+" · "+s(c.nombre),detail);String dialogText=teacher+"\n"+periodo+"\n"+s(c.descripcion);v.setOnClickListener(x->new MaterialAlertDialogBuilder(this).setTitle(c.nombre).setMessage(dialogText).setPositiveButton("Cerrar",null).show());content.addView(v);if(requested==c.id)v.performClick();}}
    private void grades(List<Nota>notes){content.addView(section("Calificaciones por curso"));if(notes.isEmpty()){content.addView(messageCard("Aún no tienes notas registradas.",false));return;}long requested=getIntent().getLongExtra("notificationDestinationId",-1);Map<String,List<Nota>>groups=new LinkedHashMap<>();for(Nota n:notes)groups.computeIfAbsent(s(n.cursoCodigo)+" · "+s(n.cursoNombre),k->new ArrayList<>()).add(n);for(Map.Entry<String,List<Nota>>e:groups.entrySet()){boolean target=false;MaterialCardView panel=new MaterialCardView(this);panel.setRadius(dp(16));panel.setCardElevation(dp(2));panel.setStrokeWidth(dp(1));panel.setStrokeColor(getColor(R.color.dashboard_border));panel.setCardBackgroundColor(getColor(R.color.dashboard_surface));LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(14),dp(18),dp(12));TextView course=text(e.getKey(),17,true);course.setTextColor(getColor(R.color.dashboard_grade));body.addView(course);View divider=new View(this);divider.setBackgroundColor(getColor(R.color.dashboard_border));LinearLayout.LayoutParams dividerParams=new LinearLayout.LayoutParams(-1,dp(1));dividerParams.topMargin=dp(7);dividerParams.bottomMargin=dp(7);body.addView(divider,dividerParams);for(Nota n:e.getValue()){target|=requested==n.id;LinearLayout row=new LinearLayout(this);row.setGravity(android.view.Gravity.CENTER_VERTICAL);TextView type=text(s(n.tipoEvaluacion),14,true);type.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));row.addView(type);TextView grade=text(n.calificacion==null?"Sin registrar":String.format(Locale.getDefault(),"%.2f",n.calificacion),14,true);grade.setTextColor(getColor(n.calificacion==null?R.color.dashboard_text_secondary:R.color.dashboard_text_primary));row.addView(grade);body.addView(row);View separator=new View(this);separator.setBackgroundColor(getColor(R.color.dashboard_border));LinearLayout.LayoutParams sep=new LinearLayout.LayoutParams(-1,dp(1));sep.topMargin=dp(6);sep.bottomMargin=dp(6);body.addView(separator,sep);}panel.addView(body);LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(-1,-2);params.bottomMargin=dp(12);panel.setLayoutParams(params);content.addView(panel);if(target){panel.setStrokeColor(getColor(R.color.dashboard_grade));panel.setStrokeWidth(dp(2));panel.requestFocus();}}}
    private void tuition(List<Colegiatura>rows){content.addView(section("Mis colegiaturas"));if(rows.isEmpty()){content.addView(messageCard("No tienes colegiaturas registradas.",false));return;}long requested=getIntent().getLongExtra("notificationDestinationId",-1);for(Colegiatura c:rows){String periodo=c.cicloNombre==null?"Año académico "+c.cicloAnio:c.cicloNombre+" · "+c.cicloAnio;View v=card(s(c.concepto)+" · "+s(c.estado),periodo+" · Vence: "+s(c.fechaVencimiento)+"\nTotal: Q"+money(c.montoTotal)+" · Pagos confirmados: Q"+money(c.montoPagado)+" · Saldo: Q"+money(c.saldoPendiente));v.setOnClickListener(x->{boolean canPay=c.activo&&c.saldoPendiente>0&&Permissions.has(Permissions.COLEGIATURAS_REGISTRAR_PAGO);MaterialAlertDialogBuilder dialog=new MaterialAlertDialogBuilder(this).setTitle(c.concepto).setMessage(periodo+"\nEstado: "+c.estado+"\nVence: "+s(c.fechaVencimiento)+"\nTotal: Q"+money(c.montoTotal)+"\nPagos confirmados: Q"+money(c.montoPagado)+"\nSaldo: Q"+money(c.saldoPendiente)).setPositiveButton(canPay?"Registrar pago":"Cerrar",(d,w)->{if(canPay)paymentDialog(c);});dialog.show();});LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.addView(v);if(c.activo&&c.saldoPendiente>0&&Permissions.has(Permissions.COLEGIATURAS_REGISTRAR_PAGO)){Button pay=new Button(this);pay.setText("Registrar pago");pay.setOnClickListener(x->paymentDialog(c));row.addView(pay);}content.addView(row);if(requested==c.id)v.performClick();}}
    private void payments(List<Pago>rows){content.addView(section("Historial de pagos"));if(rows.isEmpty()){content.addView(messageCard("No has registrado pagos para revisión.",false));return;}for(Pago p:rows)content.addView(card("Q"+money(p.monto)+" · "+s(p.estado),"Boleta: "+s(p.referencia)+" · Medio: "+s(p.metodoPago)+"\nFecha: "+s(p.fechaPago)+(p.motivoRechazo==null?"":"\nMotivo: "+p.motivoRechazo)));}
    private void paymentDialog(Colegiatura c){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),0,dp(20),0);TextInputEditText amount=input(box,"Monto pagado",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL),reference=input(box,"Número de boleta",InputType.TYPE_CLASS_TEXT),method=input(box,"Medio de pago",InputType.TYPE_CLASS_TEXT),date=input(box,"Fecha de pago",InputType.TYPE_CLASS_TEXT),proof=input(box,"Comprobante URL (opcional)",InputType.TYPE_CLASS_TEXT);date.setText(LocalDate.now().toString());date.setFocusable(false);date.setOnClickListener(v->{LocalDate today=LocalDate.now();DatePickerDialog picker=new DatePickerDialog(this,(view,y,m,d)->date.setText(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d)),today.getYear(),today.getMonthValue()-1,today.getDayOfMonth());picker.getDatePicker().setMaxDate(System.currentTimeMillis());picker.show();});String idempotencyKey=UUID.randomUUID().toString();androidx.appcompat.app.AlertDialog dialog=new MaterialAlertDialogBuilder(this).setTitle("Registrar pago").setMessage("El saldo oficial no cambiará hasta la aprobación administrativa.").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Enviar",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(x->{double value;try{value=Double.parseDouble(text(amount));}catch(Exception e){value=0;}LocalDate paidOn=null;try{paidOn=LocalDate.parse(text(date));}catch(Exception ignored){}if(value<=0||value>c.saldoPendiente||text(reference).isEmpty()||text(method).isEmpty()||paidOn==null||paidOn.isAfter(LocalDate.now())){Toast.makeText(this,"Completa boleta, medio, fecha válida y monto disponible.",Toast.LENGTH_LONG).show();return;}dialog.getButton(-1).setEnabled(false);PagoRegistro r=new PagoRegistro();r.monto=value;r.fechaPago=paidOn.toString();r.referencia=text(reference);r.metodoPago=text(method);r.comprobanteUrl=text(proof).isEmpty()?null:text(proof);r.idempotencyKey=idempotencyKey;api.registrarPago(c.id,r).enqueue(new Callback<Pago>(){public void onResponse(Call<Pago>q,Response<Pago>z){if(z.isSuccessful()){dialog.dismiss();Toast.makeText(EstudianteAcademicActivity.this,"Pago registrado. Pendiente de aprobación por administración",Toast.LENGTH_LONG).show();load();}else{dialog.getButton(-1).setEnabled(true);Toast.makeText(EstudianteAcademicActivity.this,AcademicErrors.from(EstudianteAcademicActivity.this,z),Toast.LENGTH_LONG).show();}}public void onFailure(Call<Pago>q,Throwable t){dialog.getButton(-1).setEnabled(true);Toast.makeText(EstudianteAcademicActivity.this,"No se pudo enviar. Puedes reintentar.",Toast.LENGTH_LONG).show();}});}));dialog.show();}
    private TextInputEditText input(LinearLayout box,String hint,int type){TextInputLayout wrap=new TextInputLayout(this);wrap.setHint(hint);TextInputEditText edit=new TextInputEditText(wrap.getContext());edit.setInputType(type);wrap.addView(edit);box.addView(wrap);return edit;}
    private void error(String msg){content.addView(messageCard(msg,true));Button retry=new Button(this);retry.setText("Reintentar");retry.setOnClickListener(v->load());content.addView(retry);}private synchronized void done(){if(--pending<=0)loading(false);}private<T>List<T>items(PageResponse<T>p){return p==null||p.content==null?Collections.emptyList():p.content;}private String s(String x){return x==null?"":x;}private String money(double x){return String.format(Locale.getDefault(),"%.2f",x);}private String text(EditText e){return e.getText()==null?"":e.getText().toString().trim();}
    @Override protected void onDestroy(){for(Call<?>c:calls)c.cancel();super.onDestroy();}
}
