package gt.com.ro.devumgapp.academico.ui;

import android.os.Bundle;
import android.text.InputType;
import android.view.View;
import android.widget.*;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import com.google.android.material.textfield.*;
import java.time.LocalDate;
import java.util.*;
import gt.com.ro.devumgapp.R;
import gt.com.ro.devumgapp.academico.dto.AcademicDtos.*;
import gt.com.ro.devumgapp.academico.network.AcademicoApiService;
import gt.com.ro.devumgapp.auth.ui.HomeActivity;
import gt.com.ro.devumgapp.core.dto.PageResponse;
import gt.com.ro.devumgapp.core.network.RetrofitClient;
import gt.com.ro.devumgapp.core.session.*;
import gt.com.ro.devumgapp.core.ui.ModuleNavigation;
import retrofit2.*;

/** Módulos de consulta del estudiante; todos consumen rutas /me sin aceptar un estudianteId. */
public class EstudianteAcademicActivity extends AcademicBaseActivity {
    private static final int PAGE_SIZE=200;
    private AcademicoApiService api; private int pending,mode;
    private final List<Call<?>> calls=new ArrayList<>();
    @Override protected void onCreate(Bundle state){super.onCreate(state);if(!SessionManager.getInstance().isLoggedIn()){SessionManager.handleUnauthorized(this);return;}if(!Permissions.hasRole("ESTUDIANTE")){finish();return;}setContentView(R.layout.activity_academic_overview);content=findViewById(R.id.academicContent);progress=findViewById(R.id.progressAcademic);mode=getIntent().getIntExtra(HomeActivity.EXTRA_CURRENT_DESTINATION,R.id.nav_carreras);MaterialToolbar bar=findViewById(R.id.toolbarAcademic);bar.setTitle(title());ModuleNavigation.attach(this,bar);configureHero(title(),subtitle(),hero(),icon(),R.color.dashboard_student);api=RetrofitClient.getClient().create(AcademicoApiService.class);load();}
    private String title(){if(mode==R.id.nav_cursos)return"Mis cursos";if(mode==R.id.nav_notas)return"Mis notas";if(mode==R.id.nav_colegiaturas)return"Colegiatura";return"Mi carrera";}
    private String subtitle(){if(mode==R.id.nav_cursos)return"Cursos en los que estás inscrito";if(mode==R.id.nav_notas)return"Evaluaciones registradas por curso";if(mode==R.id.nav_colegiaturas)return"Estado de cuenta y pagos en revisión";return"Plan de estudios y avance de créditos";}
    private int hero(){return mode==R.id.nav_colegiaturas?R.drawable.bg_colegiatura_header:mode==R.id.nav_notas?R.drawable.bg_nota_header:mode==R.id.nav_cursos?R.drawable.bg_curso_header:R.drawable.bg_estudiante_header;}
    private int icon(){return mode==R.id.nav_colegiaturas?R.drawable.ic_payment:mode==R.id.nav_notas?R.drawable.ic_grade:mode==R.id.nav_cursos?R.drawable.ic_course:R.drawable.ic_career;}
    private void load(){content.removeAllViews();loading(true);calls.clear();if(mode==R.id.nav_cursos)loadCourses();else if(mode==R.id.nav_notas){pending=1;request(api.notasEstudianteFiltradas(null,0,PAGE_SIZE),p->grades(items(p)));}else if(mode==R.id.nav_colegiaturas){pending=2;request(api.colegiaturas(0,PAGE_SIZE),p->tuition(items(p)));request(api.pagos(),this::payments);}else{pending=1;request(api.planCarreraEstudiante(),this::career);}}
    private void loadCourses(){pending=2;request(api.cursosInscritosEstudiante(),rows->request(api.docentesEstudiante(),teachers->courses(rows,teachers)));}
    private <T>void request(Call<T>call,java.util.function.Consumer<T>ok){calls.add(call);call.enqueue(new Callback<T>(){public void onResponse(Call<T>c,Response<T>r){if(r.isSuccessful()&&r.body()!=null)ok.accept(r.body());else error(AcademicErrors.from(EstudianteAcademicActivity.this,r));done();}public void onFailure(Call<T>c,Throwable t){if(!c.isCanceled())error("No se pudo cargar la información. Revisa tu conexión.");done();}});}
    private void career(PlanCarrera p){content.addView(section("Carrera asignada"));content.addView(card(s(p.carrera.codigo)+" · "+s(p.carrera.nombre),s(p.carrera.descripcion)));content.addView(card("Créditos del plan: "+p.totalCreditosPlan,"Créditos inscritos: "+p.totalCreditosInscritos));content.addView(section("Cursos del plan"));List<CursoPlan>rows=p.cursosDisponibles==null?Collections.emptyList():p.cursosDisponibles;if(rows.isEmpty())content.addView(messageCard("No hay cursos en el plan.",false));for(CursoPlan c:rows)content.addView(card(s(c.codigo)+" · "+s(c.nombre),c.creditos+" créditos · "+(c.inscrito?"Inscrito":"Disponible")));}
    private void courses(List<Curso>rows,List<DocenteCurso>teachers){content.addView(section("Cursos inscritos"));if(rows==null||rows.isEmpty()){content.addView(messageCard("No tienes cursos inscritos.",false));return;}for(Curso c:rows){String teacher="Sin docente asignado";for(DocenteCurso d:teachers)if(d.cursoId==c.id){teacher="Docente: "+s(d.nombre)+" "+s(d.apellido);break;}String detail=c.creditos+" créditos · "+teacher+(c.cicloAnio>0?" · Período "+c.cicloAnio:"");View v=card(s(c.codigo)+" · "+s(c.nombre),detail);String dialogText=teacher+"\n"+s(c.descripcion);v.setOnClickListener(x->new MaterialAlertDialogBuilder(this).setTitle(c.nombre).setMessage(dialogText).setPositiveButton("Cerrar",null).show());content.addView(v);}}
    private void grades(List<Nota>notes){content.addView(section("Calificaciones por curso"));if(notes.isEmpty()){content.addView(messageCard("Aún no tienes notas registradas.",false));return;}Map<String,List<Nota>>groups=new LinkedHashMap<>();for(Nota n:notes)groups.computeIfAbsent(s(n.cursoCodigo)+" · "+s(n.cursoNombre),k->new ArrayList<>()).add(n);for(Map.Entry<String,List<Nota>>e:groups.entrySet()){StringBuilder d=new StringBuilder();for(Nota n:e.getValue())d.append(s(n.tipoEvaluacion)).append(": ").append(n.calificacion==null?"Sin registrar":String.format(Locale.getDefault(),"%.2f",n.calificacion)).append('\n');content.addView(card(e.getKey(),d.toString().trim()));}}
    private void tuition(List<Colegiatura>rows){content.addView(section("Mis colegiaturas"));if(rows.isEmpty()){content.addView(messageCard("No tienes colegiaturas registradas.",false));return;}for(Colegiatura c:rows){View v=card(s(c.concepto)+" · "+s(c.estado),"Vence: "+s(c.fechaVencimiento)+"\nTotal: Q"+money(c.montoTotal)+" · Pagado: Q"+money(c.montoPagado)+" · Saldo: Q"+money(c.saldoPendiente));if(c.activo&&c.saldoPendiente>0)v.setOnClickListener(x->paymentDialog(c));content.addView(v);}}
    private void payments(List<Pago>rows){content.addView(section("Pagos declarados"));if(rows.isEmpty()){content.addView(messageCard("No has registrado pagos para revisión.",false));return;}for(Pago p:rows)content.addView(card("Q"+money(p.monto)+" · "+s(p.estado),s(p.fechaPago)+" · Ref. "+s(p.referencia)+(p.motivoRechazo==null?"":"\n"+p.motivoRechazo)));}
    private void paymentDialog(Colegiatura c){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),0,dp(20),0);TextInputEditText amount=input(box,"Monto",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL),reference=input(box,"Referencia",InputType.TYPE_CLASS_TEXT),method=input(box,"Método de pago (opcional)",InputType.TYPE_CLASS_TEXT);String idempotencyKey=UUID.randomUUID().toString();androidx.appcompat.app.AlertDialog dialog=new MaterialAlertDialogBuilder(this).setTitle("Registrar pago").setMessage("Quedará pendiente de validación y no cambiará el saldo todavía.").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Enviar",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(x->{double value;try{value=Double.parseDouble(text(amount));}catch(Exception e){value=0;}if(value<=0||value>c.saldoPendiente||text(reference).isEmpty()){Toast.makeText(this,"Ingresa monto válido y referencia.",Toast.LENGTH_LONG).show();return;}dialog.getButton(-1).setEnabled(false);PagoRegistro r=new PagoRegistro();r.monto=value;r.fechaPago=LocalDate.now().toString();r.referencia=text(reference);r.metodoPago=text(method);r.idempotencyKey=idempotencyKey;api.registrarPago(c.id,r).enqueue(new Callback<Pago>(){public void onResponse(Call<Pago>q,Response<Pago>z){if(z.isSuccessful()){dialog.dismiss();Toast.makeText(EstudianteAcademicActivity.this,"Pago enviado para revisión.",Toast.LENGTH_LONG).show();load();}else{dialog.getButton(-1).setEnabled(true);Toast.makeText(EstudianteAcademicActivity.this,AcademicErrors.from(EstudianteAcademicActivity.this,z),Toast.LENGTH_LONG).show();}}public void onFailure(Call<Pago>q,Throwable t){dialog.getButton(-1).setEnabled(true);Toast.makeText(EstudianteAcademicActivity.this,"No se pudo enviar. Puedes reintentar.",Toast.LENGTH_LONG).show();}});}));dialog.show();}
    private TextInputEditText input(LinearLayout box,String hint,int type){TextInputLayout wrap=new TextInputLayout(this);wrap.setHint(hint);TextInputEditText edit=new TextInputEditText(wrap.getContext());edit.setInputType(type);wrap.addView(edit);box.addView(wrap);return edit;}
    private void error(String msg){content.addView(messageCard(msg,true));Button retry=new Button(this);retry.setText("Reintentar");retry.setOnClickListener(v->load());content.addView(retry);}private synchronized void done(){if(--pending<=0)loading(false);}private<T>List<T>items(PageResponse<T>p){return p==null||p.content==null?Collections.emptyList():p.content;}private String s(String x){return x==null?"":x;}private String money(double x){return String.format(Locale.getDefault(),"%.2f",x);}private String text(EditText e){return e.getText()==null?"":e.getText().toString().trim();}
    @Override protected void onDestroy(){for(Call<?>c:calls)c.cancel();super.onDestroy();}
}
